from pathlib import Path
import nbformat as nbf
from textwrap import dedent

CODE_DIR=Path(__file__).resolve().parent
WORKSPACE_DIR=CODE_DIR.parents[1]
out=WORKSPACE_DIR/'Machine Note'/CODE_DIR.name
nb=nbf.v4.new_notebook()
nb.metadata.kernelspec={'display_name':'Python 3','language':'python','name':'python3'}
nb.metadata.language_info={'name':'python','version':'3'}
nb.cells=[
 nbf.v4.new_markdown_cell(dedent(r'''
 # Numerical fit of the heterotic \(SO(23)\) four-vector \(1\to3\) amplitude

 This notebook analyzes the conformal-block data generated by
 `heterotic_so23_1to3_fast.py`.  The tensor decomposition is
 \[
 \mathcal M_{a_0;a_1a_2a_3}=A\,\delta^{a_0a_3}\delta^{a_1a_2}
 +B\,\delta^{a_0a_2}\delta^{a_1a_3}
 +C\,\delta^{a_0a_1}\delta^{a_2a_3}.
 \]

 The numerical data suggest the reduced amplitude
 \[
 \boxed{
 \begin{aligned}
 A&=-\pi\frac{\omega_0\omega_1\omega_2\omega_3}
 {1+i(\omega_1+\omega_2)},\\
 B&=-\pi\frac{\omega_0\omega_1\omega_2\omega_3}
 {1+i(\omega_1+\omega_3)},\\
 C&=-\pi\frac{\omega_0\omega_1\omega_2\omega_3}
 {1+i(\omega_2+\omega_3)}.
 \end{aligned}}
 \]
 A common heterotic sphere normalization and convention-dependent phase are omitted.
 ''')),
 nbf.v4.new_code_cell(dedent('''
 from pathlib import Path
 import json, math
 import numpy as np
 import matplotlib.pyplot as plt
 from scipy.optimize import least_squares

 HERE = Path.cwd()
 WORKSPACE = HERE.parents[1] if HERE.name == 'heterotic_so23_1to3_vvvv_fit_bundle' else HERE
 ROOT = WORKSPACE/'Data Set'/'heterotic_so23_1to3_vvvv_fit_bundle'
 CODE_ROOT = WORKSPACE/'Codes'/'heterotic_so23_1to3_vvvv_fit_bundle'
 if not ROOT.exists():
     ROOT = Path('/mnt/data')
     CODE_ROOT = ROOT
 ''')),
 nbf.v4.new_markdown_cell('## Equal-outgoing Figure-3-style slice'),
 nbf.v4.new_code_cell(dedent(r'''
 equal = json.loads((ROOT/'heterotic_equal_scan_segmented_complete.json').read_text())
 rows = equal['rows']
 a = np.array([r['a'] for r in rows])
 omega = np.array([complex(*r['omega0']) for r in rows])
 A_num = np.array([complex(*r['value']) for r in rows])
 A_conj = -np.pi*omega**4/(27*(1+2j*omega/3))
 np.max(np.abs((A_num-A_conj)/A_conj)), np.sqrt(np.mean(np.abs((A_num-A_conj)/A_conj)**2))
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 aa = np.linspace(a.min(), a.max(), 500)
 ww = 1/3 + 1j*aa
 pp = -np.pi*ww**4/(27*(1+2j*ww/3))
 plt.figure(figsize=(7,4.5))
 plt.plot(aa, pp.real, label='conjecture')
 plt.scatter(a, A_num.real, label='block integral')
 plt.xlabel(r'$a$ in $\omega_0=1/3+ia$')
 plt.ylabel(r'$\mathrm{Re}\,A$')
 plt.grid(True); plt.legend(); plt.show()
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 plt.figure(figsize=(7,4.5))
 plt.plot(aa, pp.imag, label='conjecture')
 plt.scatter(a, A_num.imag, label='block integral')
 plt.xlabel(r'$a$ in $\omega_0=1/3+ia$')
 plt.ylabel(r'$\mathrm{Im}\,A$')
 plt.grid(True); plt.legend(); plt.show()
 ''')),
 nbf.v4.new_markdown_cell(dedent(r'''
 Normalize by the expected fourth-order soft factor.  With
 \(s=-i\omega_0\), define
 \[
 R(s)=\frac{A_{\rm eq}}{-\pi s^4/27}.
 \]
 We first fit the unrestricted two-real-parameter one-pole form
 \(R=\alpha/(1-\beta s)\).
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 s = -1j*omega
 R = A_num/(-np.pi*s**4/27)
 def residual(par):
     pred = par[0]/(1-par[1]*s)
     z = (pred-R)/R
     return np.r_[z.real,z.imag]
 fit = least_squares(residual, [1,2/3], xtol=1e-14, ftol=1e-14, gtol=1e-14)
 alpha, beta = fit.x
 locked = 1/(1-2*s/3)
 {
   'alpha': alpha,
   'beta': beta,
   '|alpha-1|': abs(alpha-1),
   '|beta-2/3|': abs(beta-2/3),
   'locked max relative error': np.max(abs((R-locked)/R)),
 }
 ''')),
 nbf.v4.new_markdown_cell('## Asymmetric and non-collinear kinematics'),
 nbf.v4.new_code_cell(dedent(r'''
 data = json.loads((ROOT/'heterotic_vvvv_fit_data.json').read_text())
 xs, ys, values, commons, point_ids = [], [], [], [], []
 for ip,row in enumerate(data['rows']):
     w1,w2,w3,w0 = [complex(*z) for z in row['energies']]
     pair_sums = [w1+w2,w1+w3,w2+w3]
     common = -np.pi*w0*w1*w2*w3
     for x,z in zip(pair_sums,row['value']):
         value = complex(*z)
         xs.append(x)
         ys.append(common/value)
         values.append(value)
         commons.append(common)
         point_ids.append(ip)
 xs=np.array(xs); ys=np.array(ys); values=np.array(values); commons=np.array(commons); point_ids=np.array(point_ids)
 ''')),
 nbf.v4.new_markdown_cell(dedent(r'''
 The useful linearizing variable is
 \[
 Y_{ij}\equiv\frac{-\pi\omega_0\omega_1\omega_2\omega_3}{A_{ij}}.
 \]
 Fit \(Y_{ij}=\alpha+\beta(\omega_i+\omega_j)\), allowing both
 \(\alpha\) and \(\beta\) to be arbitrary complex numbers.
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 M = np.column_stack([np.ones_like(xs),xs])
 alpha,beta = np.linalg.lstsq(M,ys,rcond=None)[0]
 pred_locked = commons/(1+1j*xs)
 rel_locked = np.abs((values-pred_locked)/pred_locked)
 {
   'alpha':alpha,
   'beta':beta,
   '|alpha-1|':abs(alpha-1),
   '|beta-i|':abs(beta-1j),
   'max locked relative error':rel_locked.max(),
   'rms locked relative error':np.sqrt(np.mean(rel_locked**2)),
 }
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 plt.figure(figsize=(6.2,5.4))
 plt.plot((1+1j*xs).real,(1+1j*xs).imag,'x',label=r'$1+i(\omega_i+\omega_j)$')
 plt.plot(ys.real,ys.imag,'o',fillstyle='none',label='normalized numerical inverse')
 plt.xlabel('real part'); plt.ylabel('imaginary part')
 plt.grid(True); plt.legend(); plt.show()
 ''')),
 nbf.v4.new_markdown_cell('## Whole-kinematic-point cross-validation'),
 nbf.v4.new_code_cell(dedent(r'''
 train = point_ids < 6
 test = ~train
 coef_train = np.linalg.lstsq(M[train],ys[train],rcond=None)[0]
 pred_cv = commons/(M@coef_train)
 rel_cv = np.abs((values-pred_cv)/pred_cv)
 {
   'fit on first six points':coef_train,
   'training max':rel_cv[train].max(),
   'held-out max':rel_cv[test].max(),
   'held-out rms':np.sqrt(np.mean(rel_cv[test]**2)),
 }
 ''')),
 nbf.v4.new_markdown_cell(dedent(r'''
 ## Resonance and soft checks

 At \(\omega_0=i\), energy conservation gives
 \(1+i(\omega_i+\omega_j)=-i\omega_k\).  The conjecture therefore becomes
 \(A_{ij}=\pi\omega_i\omega_j\), exactly reproducing the independently
 computed resonance result.  Away from resonance the common product makes
 the amplitude vanish linearly as any external energy is taken soft.
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 def conjectured_coefficients(energies):
     w1,w2,w3,w0=map(complex,energies)
     common=-np.pi*w0*w1*w2*w3
     return np.array([
       common/(1+1j*(w1+w2)),
       common/(1+1j*(w1+w3)),
       common/(1+1j*(w2+w3)),
     ])

 w1,w2 = 0.2j,0.3j
 w3 = 1j-w1-w2
 conjectured_coefficients([w1,w2,w3,1j]), np.pi*np.array([w1*w2,w1*w3,w2*w3])
 ''')),
 nbf.v4.new_markdown_cell(dedent(r'''
 ## Optional expensive worldsheet evaluation

 The following cell recomputes one asymmetric point from the super-Liouville
 structure constants, central-charge-recursion blocks, the regularized
 cross-ratio integral, and a segmented internal-momentum quadrature.  It is
 disabled by default because it takes tens of seconds.
 ''')),
 nbf.v4.new_code_cell(dedent(r'''
 if False:
     import sys
     sys.path.insert(0,str(CODE_ROOT))
     from heterotic_so23_1to3_fast import vector_amplitude_coefficients_regularized
     w0=1/3+0.6j
     energies=[0.2*w0,0.3*w0,0.5*w0,w0]
     numerical=vector_amplitude_coefficients_regularized(
       energies,q_order=6,p_nodes='segmented',p_max=4.0,
       epsilon0=.08,epsilon1=.06,theta_orders=(24,24,60),radial_order=24,
       disk_total_order=17,lens_radial_order=20,lens_angular_order=64,lens_power=3.0)
     numerical, conjectured_coefficients(energies)
 ''')),
]
nbf.write(nb,out/'heterotic_so23_1to3_vvvv_fit.ipynb')
print('notebook written')
