"""Stress exact-c NS super-Liouville crossing with the sphere c-recursion.

For four bottom-component NS primaries in the ordering

    <V_P4(infinity) V_P3(1) V_P2(z,zbar) V_P1(0)>,

the script compares the two continuum decompositions

    G_4321(z,zbar) = G_4123(1-z,1-zbar).

Each side includes the BRY b=1 structure constants, the dP/pi spectral
measure, and both the even and odd NS families.  The conformal blocks are
generated by the multiprecision central-charge recursion directly at
c=27/2 (hat c=9).  Every recursion leaf is the exact hypergeometric global
osp(1|2) block: no descendant Gram matrix, local-z series, elliptic-q series,
displaced-c regulator, or h-recursion is used.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import html
import json
import math
from pathlib import Path
from typing import Iterable, Sequence

from sphere_four_point import BRYNSFourPointCorrelator


DEFAULT_MOMENTA = (0.5, 1.0 / 3.0, 0.25, 0.6)
DEFAULT_Z_VALUES = tuple(index / 20.0 for index in range(6, 15))
DATA_ROOT = Path(__file__).resolve().parent.parent / "Data Set"


@dataclass(frozen=True)
class CrossingResult:
    """One exact-c comparison at fixed recursion order and cross ratio."""

    recursion_order: int
    z: float
    left: complex
    right: complex

    @property
    def absolute_residual(self) -> float:
        return abs(self.left - self.right)

    @property
    def relative_residual(self) -> float:
        return self.absolute_residual / max(
            abs(self.left), abs(self.right), 1.0e-300
        )

    def json_record(self) -> dict:
        return {
            "recursion_order": self.recursion_order,
            "recursion_twice_level": 2 * self.recursion_order,
            "z": self.z,
            "left": [self.left.real, self.left.imag],
            "right": [self.right.real, self.right.imag],
            "absolute_residual": self.absolute_residual,
            "relative_residual": self.relative_residual,
        }


def _parse_csv(text: str, caster) -> tuple:
    return tuple(caster(item.strip()) for item in text.split(",") if item.strip())


def crossing_scan(
    *,
    momenta: Sequence[float] = DEFAULT_MOMENTA,
    recursion_orders: Iterable[int] = (12,),
    z_values: Sequence[float] = DEFAULT_Z_VALUES,
    structure_precision: int = 35,
    block_working_precision: int = 80,
    p_max: float = 5.0,
    quadrature_order: int = 40,
) -> list[CrossingResult]:
    """Return the full exact-c crossing ledger."""

    if len(momenta) != 4:
        raise ValueError("momenta must contain p1,p2,p3,p4")
    p1, p2, p3, p4 = map(float, momenta)
    points = tuple(float(z) for z in z_values)
    if any(not 0.0 < z < 1.0 for z in points):
        raise ValueError("the real crossing grid must satisfy 0 < z < 1")

    orders = tuple(recursion_orders)
    if not orders:
        raise ValueError("recursion_orders must not be empty")
    if any(not isinstance(order, int) or order < 0 for order in orders):
        raise ValueError("recursion_orders must contain nonnegative integers")

    # The block objects and structure constants are reused, but every value is
    # a direct c-recursion whose leaves are exact global osp(1|2) blocks.
    common = dict(
        c_recursion_order=orders[0],
        structure_precision=structure_precision,
        central_charge_shift=0.0,
        block_working_precision=block_working_precision,
    )
    direct = BRYNSFourPointCorrelator(
        p1=p1, p2=p2, p3=p3, p4=p4, **common
    )
    crossed = BRYNSFourPointCorrelator(
        p1=p3, p2=p2, p3=p1, p4=p4, **common
    )

    results: list[CrossingResult] = []
    for recursion_order in orders:
        direct.c_recursion_order = recursion_order
        crossed.c_recursion_order = recursion_order
        left_values = direct.evaluate_g_grid(
            points, p_max=p_max, quadrature_order=quadrature_order
        )
        right_values = crossed.evaluate_g_grid(
            tuple(1.0 - z for z in points),
            p_max=p_max,
            quadrature_order=quadrature_order,
        )
        for z, left, right in zip(points, left_values, right_values):
            results.append(
                CrossingResult(
                    recursion_order=recursion_order,
                    z=z,
                    left=complex(left),
                    right=complex(right),
                )
            )
    return results


def _nice_ticks(low: float, high: float, count: int = 5) -> tuple[float, ...]:
    if high <= low:
        return (low,)
    raw = (high - low) / max(1, count - 1)
    exponent = 10.0 ** math.floor(math.log10(raw))
    fraction = raw / exponent
    step = (
        1.0 if fraction <= 1.0 else 2.0 if fraction <= 2.0 else 5.0
    ) * exponent
    first = math.ceil(low / step) * step
    values = []
    value = first
    while value <= high + 1.0e-12 * max(1.0, abs(high)):
        values.append(value)
        value += step
    return tuple(values)


def _svg_path(
    x_values: Sequence[float],
    y_values: Sequence[float],
    x_map,
    y_map,
) -> str:
    return " ".join(
        ("M" if index == 0 else "L")
        + f"{x_map(x_value):.3f},{y_map(y_value):.3f}"
        for index, (x_value, y_value) in enumerate(zip(x_values, y_values))
    )


def render_svg(ledger: dict, output: Path) -> None:
    """Plot the independently evaluated channels and their signed residual."""

    orders = ledger["parameters"]["recursion_orders"]
    final_order = max(orders)
    rows = sorted(
        (
            row
            for row in ledger["rows"]
            if row["recursion_order"] == final_order
        ),
        key=lambda row: row["z"],
    )
    if len(rows) < 2:
        raise ValueError("the crossing plot requires at least two z values")

    z_values = [float(row["z"]) for row in rows]
    s_values = [float(row["left"][0]) for row in rows]
    t_values = [float(row["right"][0]) for row in rows]
    signed_relative = [
        (s_value - t_value) / max(abs(s_value), abs(t_value), 1.0e-300)
        for s_value, t_value in zip(s_values, t_values)
    ]

    width, height = 1240, 590
    panel_width, panel_height = 500, 360
    top, left_main, left_residual = 105, 90, 700
    z_low, z_high = min(z_values), max(z_values)
    y_low, y_high = min(s_values + t_values), max(s_values + t_values)
    y_pad = 0.08 * max(y_high - y_low, abs(y_high), 1.0e-12)
    y_low -= y_pad
    y_high += y_pad
    residual_limit = 1.12 * max(max(map(abs, signed_relative)), 1.0e-16)

    momenta = ledger["parameters"]["momenta"]
    momenta_text = ", ".join(f"{value:.6g}" for value in momenta)
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="white"/>',
        '<style>text{font-family:Arial,sans-serif;fill:#191919}'
        '.axis{stroke:#333;stroke-width:1}.grid{stroke:#ddd;stroke-width:1}'
        '.tick{font-size:13px}.label{font-size:16px}.legend{font-size:13px}'
        '.s{fill:none;stroke:#111;stroke-width:3}'
        '.t{fill:none;stroke:#2754b8;stroke-width:2.5;stroke-dasharray:8 4}'
        '.r{fill:none;stroke:#b23a48;stroke-width:2.5}</style>',
        '<text x="620" y="29" text-anchor="middle" font-size="21">'
        'NS Liouville sphere crossing at ĉ=9</text>',
        '<text x="620" y="55" text-anchor="middle" font-size="14">'
        f'exact c=27/2 direct recursion, order {final_order}; '
        f'P=({html.escape(momenta_text)})</text>',
    ]

    def draw_axes(
        left: float,
        vertical_low: float,
        vertical_high: float,
        title: str,
        *,
        scientific: bool = False,
    ):
        x_map = lambda value: left + panel_width * (value - z_low) / (z_high - z_low)
        y_map = lambda value: top + panel_height * (
            vertical_high - value
        ) / (vertical_high - vertical_low)
        parts.append(
            f'<text x="{left + panel_width / 2}" y="{top - 18}" '
            f'text-anchor="middle" class="label">{html.escape(title)}</text>'
        )
        for tick in _nice_ticks(vertical_low, vertical_high, 6):
            y = y_map(tick)
            label = f"{tick:.1e}" if scientific else f"{tick:.3g}"
            parts.append(
                f'<line x1="{left}" y1="{y:.3f}" x2="{left + panel_width}" '
                f'y2="{y:.3f}" class="grid"/>'
            )
            parts.append(
                f'<text x="{left - 10}" y="{y + 4:.3f}" text-anchor="end" '
                f'class="tick">{label}</text>'
            )
        for tick in _nice_ticks(z_low, z_high, 6):
            x = x_map(tick)
            parts.append(
                f'<line x1="{x:.3f}" y1="{top}" x2="{x:.3f}" '
                f'y2="{top + panel_height}" class="grid"/>'
            )
            parts.append(
                f'<text x="{x:.3f}" y="{top + panel_height + 23}" '
                f'text-anchor="middle" class="tick">{tick:.2f}</text>'
            )
        parts.append(
            f'<line x1="{left}" y1="{top + panel_height}" '
            f'x2="{left + panel_width}" y2="{top + panel_height}" class="axis"/>'
        )
        parts.append(
            f'<line x1="{left}" y1="{top}" x2="{left}" '
            f'y2="{top + panel_height}" class="axis"/>'
        )
        parts.append(
            f'<text x="{left + panel_width / 2}" y="{top + panel_height + 53}" '
            'text-anchor="middle" class="label">z</text>'
        )
        return x_map, y_map

    x_main, y_main = draw_axes(
        left_main, y_low, y_high, "Independent s- and t-channel sums"
    )
    parts.append(
        f'<path d="{_svg_path(z_values, s_values, x_main, y_main)}" class="s"/>'
    )
    parts.append(
        f'<path d="{_svg_path(z_values, t_values, x_main, y_main)}" class="t"/>'
    )

    x_residual, y_residual = draw_axes(
        left_residual,
        -residual_limit,
        residual_limit,
        "Signed relative difference (s−t)/max(|s|,|t|)",
        scientific=True,
    )
    parts.append(
        f'<line x1="{left_residual}" y1="{y_residual(0):.3f}" '
        f'x2="{left_residual + panel_width}" y2="{y_residual(0):.3f}" class="axis"/>'
    )
    parts.append(
        f'<path d="{_svg_path(z_values, signed_relative, x_residual, y_residual)}" '
        'class="r"/>'
    )

    legend_y = 570
    legend = (
        ("s: G₄₃₂₁(z)", "#111", False),
        ("t: G₄₁₂₃(1−z)", "#2754b8", True),
        ("signed residual", "#b23a48", False),
    )
    for index, (label, color, dashed) in enumerate(legend):
        x = 300 + index * 250
        dash = ' stroke-dasharray="8 4"' if dashed else ""
        parts.append(
            f'<line x1="{x}" y1="{legend_y - 5}" x2="{x + 24}" '
            f'y2="{legend_y - 5}" stroke="{color}" stroke-width="3"{dash}/>'
        )
        parts.append(
            f'<text x="{x + 31}" y="{legend_y}" class="legend">'
            f'{html.escape(label)}</text>'
        )

    parts.append("</svg>")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts) + "\n", encoding="utf-8")


def build_ledger(
    *,
    momenta: Sequence[float] = DEFAULT_MOMENTA,
    recursion_orders: Iterable[int] = (12,),
    z_values: Sequence[float] = DEFAULT_Z_VALUES,
    structure_precision: int = 35,
    block_working_precision: int = 80,
    p_max: float = 5.0,
    quadrature_order: int = 40,
) -> dict:
    """Build a JSON-serializable result and convergence summary."""

    orders = tuple(recursion_orders)
    results = crossing_scan(
        momenta=momenta,
        recursion_orders=orders,
        z_values=z_values,
        structure_precision=structure_precision,
        block_working_precision=block_working_precision,
        p_max=p_max,
        quadrature_order=quadrature_order,
    )
    maxima = {
        str(order): max(
            result.relative_residual
            for result in results
            if result.recursion_order == order
        )
        for order in orders
    }
    return {
        "parameters": {
            "hat_c": 9.0,
            "c": 13.5,
            "b": 1.0,
            "momenta": list(map(float, momenta)),
            "recursion_orders": list(orders),
            "recursion_order_unit": "maximum accumulated physical null level",
            "recursion_twice_levels": [2 * order for order in orders],
            "z_values": list(map(float, z_values)),
            "structure_precision": structure_precision,
            "block_working_precision": block_working_precision,
            "p_max": p_max,
            "quadrature_order": quadrature_order,
            "central_charge_shift": 0.0,
            "spectral_measure": "dP/pi",
            "block_evaluation": "direct-c-recursion-with-exact-global-leaves",
            "series_truncation": None,
        },
        "max_relative_residual_by_recursion_order": maxima,
        "rows": [result.json_record() for result in results],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--momenta", default="0.5,0.3333333333333333,0.25,0.6")
    parser.add_argument(
        "--orders",
        default="12",
        help="maximum accumulated Kac level in the direct c-recursion",
    )
    parser.add_argument(
        "--z",
        default=",".join(f"{value:.2f}" for value in DEFAULT_Z_VALUES),
        help="comma-separated real cross ratios in 0<z<1",
    )
    parser.add_argument("--structure-precision", type=int, default=35)
    parser.add_argument("--block-working-precision", type=int, default=80)
    parser.add_argument("--p-max", type=float, default=5.0)
    parser.add_argument("--quadrature-order", type=int, default=40)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--plot-output",
        type=Path,
        default=DATA_ROOT / "ns_liouville_crossing_direct_c_recursion.svg",
    )
    parser.add_argument(
        "--no-plot",
        action="store_true",
        help="write only the numerical ledger",
    )
    args = parser.parse_args()

    ledger = build_ledger(
        momenta=_parse_csv(args.momenta, float),
        recursion_orders=_parse_csv(args.orders, int),
        z_values=_parse_csv(args.z, float),
        structure_precision=args.structure_precision,
        block_working_precision=args.block_working_precision,
        p_max=args.p_max,
        quadrature_order=args.quadrature_order,
    )
    payload = json.dumps(ledger, indent=2, sort_keys=True)
    if args.output is None:
        print(payload)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(payload + "\n", encoding="utf-8")
        print(args.output)
    if not args.no_plot:
        render_svg(ledger, args.plot_output)
        print(args.plot_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
