#!/usr/bin/env python3
"""Prepare the deterministic atlas-selected genus-two period-table manifest.

This module evaluates no finite-q period matrix.  It draws invariant-domain
Omega targets, selects useful theta/glasses markings, and emits their leading
q coordinates plus deterministic cusp descendants.
"""

from __future__ import annotations

import argparse
import cmath
import csv
import hashlib
import json
import math
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Iterator, Literal, Sequence

import numpy as np
from scipy.stats import qmc

try:
    from genus2_hybrid_period_map import plumbing_geometry
    from genus2_period_table_selector import SelectedAtlasPoint, iter_selected_atlas_points
except ImportError:  # pragma: no cover - package-style execution
    from plumbing.genus2_hybrid_period_map import plumbing_geometry
    from plumbing.genus2_period_table_selector import SelectedAtlasPoint, iter_selected_atlas_points


Topology = Literal["theta", "glasses"]
SCHEMA_VERSION = 1
USEFUL_REGION_SELECTOR_IMPLEMENTED = True
THIS_FILE = Path(__file__).resolve()
DEFAULT_CONFIG = THIS_FILE.parent / "config" / "genus2_period_table_cluster.json"
DEFAULT_OUTPUT = THIS_FILE.parent / "results" / "genus2_period_table" / "design_v1"


@dataclass(frozen=True)
class BackendPlan:
    backend: str
    precision_tier: str
    reason: str
    estimated_cost: float


def _canonical_json(payload: object) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def config_sha256(payload: object) -> str:
    return hashlib.sha256(_canonical_json(payload).encode("utf-8")).hexdigest()


def load_config(path: Path | str = DEFAULT_CONFIG) -> dict[str, object]:
    payload = json.loads(Path(path).read_text())
    validate_config(payload)
    return payload


def validate_config(payload: dict[str, object]) -> None:
    if int(payload.get("schema_version", -1)) != SCHEMA_VERSION:
        raise ValueError(f"period-table config must use schema version {SCHEMA_VERSION}")
    if int(payload.get("array_task_count", 0)) < 1:
        raise ValueError("array_task_count must be positive")
    if int(payload.get("seed", -1)) < 0:
        raise ValueError("seed must be nonnegative")
    useful_region = payload.get("useful_region")
    if not isinstance(useful_region, dict):
        raise ValueError("useful_region must be an object")
    if useful_region.get("mode") != "atlas-selected-theta-glasses-union":
        raise ValueError("useful_region must select the theta/glasses hybrid-cover union")
    if useful_region.get("candidate_pool_only") is not False:
        raise ValueError("the production grid must be generated by the atlas selector")
    if useful_region.get("retain_theta_glasses_overlap") is not True:
        raise ValueError("the useful-region selector must retain theta/glasses overlap")
    if not str(useful_region.get("status", "")):
        raise ValueError("useful_region.status must be explicit")
    atlas_design = payload.get("atlas_design")
    if not isinstance(atlas_design, dict):
        raise ValueError("atlas_design must be an object")
    for key in ("target_sample_power", "selector_batch_size", "search_depth", "tail_search_depth", "rescue_search_depth", "markings_per_topology", "tail_markings_per_topology", "rescue_markings_per_topology"):
        if int(atlas_design.get(key, 0)) < 1:
            raise ValueError(f"atlas_design.{key} must be positive")
    if int(atlas_design["tail_search_depth"]) < int(atlas_design["search_depth"]):
        raise ValueError("atlas tail search cannot be shallower than its primary search")
    if int(atlas_design["rescue_search_depth"]) < int(atlas_design["tail_search_depth"]):
        raise ValueError("atlas rescue search cannot be shallower than its tail search")
    for key in ("overlap_score_ratio", "overlap_q_abs_max", "tail_refine_q_abs_min", "minimum_selector_geometry_margin"):
        if float(atlas_design.get(key, 0.0)) <= 0.0:
            raise ValueError(f"atlas_design.{key} must be positive")
    if float(atlas_design["overlap_score_ratio"]) < 1.0:
        raise ValueError("atlas overlap score ratio cannot be below one")
    for key in ("required_selected_target_fraction", "cusp_augmentation_fraction"):
        value = float(atlas_design.get(key, math.nan))
        if not math.isfinite(value) or not 0.0 <= value <= 1.0:
            raise ValueError(f"atlas_design.{key} must lie in [0,1]")
    patterns = atlas_design.get("cusp_augmentation_patterns")
    if not isinstance(patterns, list) or any(
        not isinstance(pattern, list)
        or not pattern
        or any(int(edge) not in (0, 1, 2) for edge in pattern)
        for pattern in patterns
    ):
        raise ValueError("invalid atlas cusp-augmentation patterns")
    domain = payload.get("q_domain")
    if not isinstance(domain, dict):
        raise ValueError("q_domain must be an object")
    required_positive = (
        "q_abs_max",
        "q_abs_tail_min",
        "finite_q_abs_min",
        "geometry_margin_min",
        "geometry_refinement_margin",
        "standard_collocation_min_q",
    )
    for key in required_positive:
        value = float(domain.get(key, math.nan))
        if not math.isfinite(value) or value <= 0.0:
            raise ValueError(f"q_domain.{key} must be positive and finite")
    q_tail = float(domain["q_abs_tail_min"])
    q_finite = float(domain["finite_q_abs_min"])
    q_max = float(domain["q_abs_max"])
    if not q_tail < q_finite < q_max < 1.0:
        raise ValueError("require q_abs_tail_min < finite_q_abs_min < q_abs_max < 1")
    tail = payload.get("noncompact_tail")
    if not isinstance(tail, dict):
        raise ValueError("noncompact_tail must be an object")
    if float(tail.get("table_q_abs_floor", math.nan)) != q_tail:
        raise ValueError("noncompact tail floor must equal q_domain.q_abs_tail_min")
    if float(tail.get("required_boundary_stability", 0.0)) <= 0.0:
        raise ValueError("noncompact tail stability bar must be positive")
    thresholds = payload.get("schottky_all_small_q_max")
    if not isinstance(thresholds, dict):
        raise ValueError("schottky_all_small_q_max must be an object")
    for topology in ("theta", "glasses"):
        value = float(thresholds.get(topology, math.nan))
        if not q_tail < value <= q_max:
            raise ValueError(f"invalid all-small threshold for {topology}")
    strata = payload.get("strata")
    if not isinstance(strata, list) or not strata:
        raise ValueError("strata must be a nonempty list")
    known_roles = {"finite", "cusp", "small", "method_boundary", "high"}
    names: set[str] = set()
    for raw in strata:
        if not isinstance(raw, dict):
            raise ValueError("each stratum must be an object")
        name = str(raw.get("name", ""))
        if not name or name in names:
            raise ValueError("stratum names must be nonempty and unique")
        names.add(name)
        power = int(raw.get("sobol_power", -1))
        if power < 0 or power > 30:
            raise ValueError(f"invalid Sobol power for stratum {name}")
        patterns = raw.get("patterns")
        if not isinstance(patterns, list) or not patterns:
            raise ValueError(f"stratum {name} needs at least one role pattern")
        for pattern in patterns:
            if (
                not isinstance(pattern, list)
                or len(pattern) != 3
                or any(str(role) not in known_roles for role in pattern)
            ):
                raise ValueError(f"invalid role pattern in stratum {name}")
        for key in ("geometry_margin_min", "geometry_margin_max"):
            if key in raw and float(raw[key]) <= 0.0:
                raise ValueError(f"{name}.{key} must be positive")
    numerics = payload.get("numerics")
    if not isinstance(numerics, dict):
        raise ValueError("numerics must be an object")
    for key in (
        "period_tolerance",
        "agreement_tolerance",
        "schottky_tail_safety_factor",
        "crosscheck_min_q",
        "crosscheck_min_geometry_margin",
    ):
        value = float(numerics.get(key, math.nan))
        if not math.isfinite(value) or value <= 0.0:
            raise ValueError(f"numerics.{key} must be positive and finite")
    if int(numerics.get("maximum_collocation_basis", 0)) < 8:
        raise ValueError("numerics.maximum_collocation_basis is too small")
    minimum_word = int(numerics.get("minimum_schottky_word", 0))
    maximum_word = int(numerics.get("maximum_schottky_word", 0))
    if not 2 <= minimum_word <= maximum_word:
        raise ValueError("invalid numerics Schottky word interval")
    fraction = float(numerics.get("crosscheck_bulk_fraction", math.nan))
    if not math.isfinite(fraction) or not 0.0 <= fraction <= 1.0:
        raise ValueError("numerics.crosscheck_bulk_fraction must lie in [0,1]")
    crosscheck_strata = numerics.get("crosscheck_strata")
    if not isinstance(crosscheck_strata, list) or any(
        str(name) not in names for name in crosscheck_strata
    ):
        raise ValueError("numerics.crosscheck_strata must name configured strata")
    coverage = payload.get("coverage_targets")
    if not isinstance(coverage, dict):
        raise ValueError("coverage_targets must be an object")
    for key in (
        "required_target_coverage_fraction",
        "coverage_spacing_quantile",
        "roundtrip_validation_fraction",
        "refine_largest_omega_holes_fraction",
    ):
        value = float(coverage.get(key, math.nan))
        if not math.isfinite(value) or not 0.0 < value <= 1.0:
            raise ValueError(f"coverage_targets.{key} must lie in (0,1]")
    if float(coverage.get("coverage_distance_multiplier", 0.0)) <= 0.0:
        raise ValueError("coverage distance multiplier must be positive")
    for key in ("nearest_neighbor_count", "marking_search_depth", "markings_per_topology"):
        if int(coverage.get(key, 0)) < 1:
            raise ValueError(f"coverage_targets.{key} must be positive")
    cluster = payload.get("cluster")
    if not isinstance(cluster, dict):
        raise ValueError("cluster must be an object")
    if str(cluster.get("partition", "")) != "serial_requeue":
        raise ValueError("the Cannon production partition must be serial_requeue")
    concurrency = int(cluster.get("maximum_concurrent_tasks", 0))
    if not 1 <= concurrency <= int(payload["array_task_count"]):
        raise ValueError("cluster maximum_concurrent_tasks must fit the array")
    if int(cluster.get("cpus_per_task", 0)) != 1:
        raise ValueError("the period-table worker is configured for one CPU per task")
    if int(cluster.get("memory_gb_per_task", 0)) < 4:
        raise ValueError("cluster memory_gb_per_task must be at least 4 GB")
    storage = payload.get("storage")
    if not isinstance(storage, dict):
        raise ValueError("storage must be an object")
    if storage.get("working_tier") != "shared-scratch":
        raise ValueError("live shards must use shared scratch so requeued jobs can resume")
    if storage.get("checksum_algorithm") != "sha256":
        raise ValueError("the period-table archive requires SHA-256 checksums")


def nominal_point_count(payload: dict[str, object]) -> int:
    design = payload["atlas_design"]  # type: ignore[index]
    targets = 1 << int(design["target_sample_power"])
    base_upper = 2 * max(
        int(design["markings_per_topology"]),
        int(design["tail_markings_per_topology"]),
        int(design["rescue_markings_per_topology"]),
    ) * targets
    augmentation_upper = int(
        math.ceil(
            targets
            * float(design["cusp_augmentation_fraction"])
            * len(design["cusp_augmentation_patterns"])
        )
    )
    return base_upper + augmentation_upper


def _role_bounds(
    role: str,
    topology: Topology,
    payload: dict[str, object],
) -> tuple[float, float]:
    domain = payload["q_domain"]  # type: ignore[index]
    q_tail = float(domain["q_abs_tail_min"])
    q_finite = float(domain["finite_q_abs_min"])
    q_max = float(domain["q_abs_max"])
    small = float(payload["schottky_all_small_q_max"][topology])  # type: ignore[index]
    if role == "finite":
        interval = (q_finite, q_max)
    elif role == "cusp":
        interval = (q_tail, q_finite)
    elif role == "small":
        interval = (q_tail, small)
    elif role == "method_boundary":
        width = float(payload["method_boundary_log_half_width"])
        interval = (small * math.exp(-width), min(q_max, small * math.exp(width)))
    elif role == "high":
        interval = (float(payload["high_q_abs_min"]), q_max)
    else:  # pragma: no cover - validate_config excludes this
        raise ValueError(f"unknown radial role {role!r}")
    low, high = interval
    if not 0.0 < low < high < 1.0:
        raise ValueError(f"invalid radial interval {interval} for role {role}")
    return math.log(low), math.log(high)


def plan_backend(
    topology: Topology,
    q_abs: Sequence[float],
    geometry_margin: float,
    payload: dict[str, object],
) -> BackendPlan:
    """Choose the planned table backend without performing a period solve."""

    q_min = min(float(value) for value in q_abs)
    q_max = max(float(value) for value in q_abs)
    schottky_max = float(payload["schottky_all_small_q_max"][topology])  # type: ignore[index]
    domain = payload["q_domain"]  # type: ignore[index]
    if q_max <= schottky_max:
        # Word-tail certification remains mandatory at execution time.  A
        # failed Schottky certificate is promoted to the MP-collocation queue.
        return BackendPlan(
            backend="adaptive-schottky",
            precision_tier="multiprecision",
            reason="all three sewing parameters lie in the small-q Schottky region",
            estimated_cost=2.0 + 20.0 * (q_max / schottky_max) ** 3,
        )
    standard_floor = float(domain["standard_collocation_min_q"])
    comfortable_margin = float(domain["geometry_refinement_margin"])
    if q_min < standard_floor or geometry_margin < comfortable_margin:
        return BackendPlan(
            backend="holomorphic-form-collocation",
            precision_tier="multiprecision-rescaled",
            reason="mixed cusp or near-boundary geometry requires the high-precision solver",
            estimated_cost=40.0,
        )
    return BackendPlan(
        backend="holomorphic-form-collocation",
        precision_tier="binary64-adaptive",
        reason="ordinary finite-q bulk chart",
        estimated_cost=8.0 + 24.0 * (q_max / float(domain["q_abs_max"])) ** 2,
    )


def _complex_string(log_abs: float, phase: float) -> str:
    value = math.exp(float(log_abs)) * complex(math.cos(phase), math.sin(phase))
    return f"{value.real:+.17e}{value.imag:+.17e}j"


def _stable_shard(row_id: str, task_count: int) -> int:
    digest = hashlib.blake2b(row_id.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") % int(task_count)


def _stable_fraction(label: str) -> float:
    digest = hashlib.blake2b(label.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, "big") / float(1 << 64)


def _atlas_variants(
    point: SelectedAtlasPoint,
    payload: dict[str, object],
) -> Iterator[tuple[str, tuple[complex, complex, complex], tuple[complex, complex, complex]]]:
    """Yield the selected chart and deterministic cusp descendants."""

    yield "base", point.q, point.log_q
    design = payload["atlas_design"]  # type: ignore[index]
    label = f"{point.target_index}:{point.topology}:{point.marking_matrix_index}"
    if point.overlap_chart or _stable_fraction(label) >= float(
        design["cusp_augmentation_fraction"]
    ):
        return
    log_floor = math.log(float(payload["q_domain"]["q_abs_tail_min"]))  # type: ignore[index]
    for raw_pattern in design["cusp_augmentation_patterns"]:
        pattern = tuple(sorted({int(edge) for edge in raw_pattern}))
        logs = list(point.log_q)
        for edge in pattern:
            logs[edge] = complex(log_floor, logs[edge].imag)
        q_values = tuple(cmath.exp(value) for value in logs)
        suffix = "cusp-" + "".join(str(edge + 1) for edge in pattern)
        yield suffix, q_values, tuple(logs)  # type: ignore[arg-type]


def _atlas_stratum(
    topology: Topology,
    q_abs: tuple[float, float, float],
    variant: str,
    payload: dict[str, object],
) -> str:
    if variant.startswith("cusp-"):
        edge_count = len(variant.removeprefix("cusp-"))
        return {1: "one-cusp", 2: "two-cusp", 3: "all-small"}[edge_count]
    small = float(payload["schottky_all_small_q_max"][topology])  # type: ignore[index]
    if max(q_abs) <= small:
        return "all-small"
    width = float(payload["method_boundary_log_half_width"])
    if abs(math.log(max(q_abs) / small)) <= width:
        return "method-boundary"
    return "bulk"


def _iter_pattern_rows(
    *,
    topology: Topology,
    topology_index: int,
    stratum: dict[str, object],
    stratum_index: int,
    pattern: Sequence[str],
    pattern_index: int,
    payload: dict[str, object],
    digest: str,
) -> Iterator[dict[str, object]]:
    seed = (
        int(payload["seed"])
        + 100_000 * topology_index
        + 1_000 * stratum_index
        + pattern_index
    )
    power = int(stratum["sobol_power"])
    design = qmc.Sobol(6, scramble=True, seed=seed).random_base2(power)
    log_bounds = tuple(_role_bounds(str(role), topology, payload) for role in pattern)
    phase_min = -math.pi
    phase_width = 2.0 * math.pi
    minimum_margin = max(
        float(payload["q_domain"]["geometry_margin_min"]),  # type: ignore[index]
        float(stratum.get("geometry_margin_min", 0.0)),
    )
    maximum_margin = float(stratum.get("geometry_margin_max", math.inf))
    task_count = int(payload["array_task_count"])
    for sobol_index, unit in enumerate(design):
        log_abs = tuple(
            low + float(unit[edge]) * (high - low)
            for edge, (low, high) in enumerate(log_bounds)
        )
        phases = tuple(phase_min + phase_width * float(unit[edge + 3]) for edge in range(3))
        q_values = tuple(
            math.exp(log_value) * complex(math.cos(phase), math.sin(phase))
            for log_value, phase in zip(log_abs, phases)
        )
        geometry = plumbing_geometry(topology, q_values)
        if not (minimum_margin <= geometry.minimum_margin <= maximum_margin):
            continue
        q_abs = tuple(math.exp(value) for value in log_abs)
        backend = plan_backend(topology, q_abs, geometry.minimum_margin, payload)
        row_id = (
            f"{topology}-{stratum['name']}-p{pattern_index:02d}-"
            f"s{sobol_index:09d}"
        )
        yield {
            "schema_version": SCHEMA_VERSION,
            "config_sha256": digest,
            "row_id": row_id,
            "topology": topology,
            "stratum": str(stratum["name"]),
            "pattern_index": pattern_index,
            "sobol_index": sobol_index,
            "design_seed": seed,
            "q1": _complex_string(log_abs[0], phases[0]),
            "q2": _complex_string(log_abs[1], phases[1]),
            "q3": _complex_string(log_abs[2], phases[2]),
            "log_abs_q1": log_abs[0],
            "log_abs_q2": log_abs[1],
            "log_abs_q3": log_abs[2],
            "phase_q1": phases[0],
            "phase_q2": phases[1],
            "phase_q3": phases[2],
            "q_min": min(q_abs),
            "q_max": max(q_abs),
            "geometry_margin": geometry.minimum_margin,
            "planned_backend": backend.backend,
            "precision_tier": backend.precision_tier,
            "backend_reason": backend.reason,
            "estimated_cost": backend.estimated_cost,
            "shard_id": _stable_shard(row_id, task_count),
        }


def iter_manifest_rows(payload: dict[str, object]) -> Iterator[dict[str, object]]:
    """Yield the atlas-selected theta/glasses union without evaluating ``Omega(q)``."""

    digest = config_sha256(payload)
    task_count = int(payload["array_task_count"])
    seen: set[tuple[object, ...]] = set()
    for point in iter_selected_atlas_points(payload):
        for variant, q_values, logs in _atlas_variants(point, payload):
            geometry = plumbing_geometry(point.topology, q_values, log_q_values=logs)
            minimum_margin = float(payload["q_domain"]["geometry_margin_min"])  # type: ignore[index]
            if geometry.minimum_margin < minimum_margin:
                continue
            key = (
                point.topology,
                *(round(value.real, 14) for value in logs),
                *(round(math.remainder(value.imag, 2.0 * math.pi), 14) for value in logs),
            )
            if key in seen:
                continue
            seen.add(key)
            q_abs = tuple(math.exp(value.real) for value in logs)
            backend = plan_backend(point.topology, q_abs, geometry.minimum_margin, payload)
            row_id = (
                f"{point.topology}-target-{point.target_index:07d}-"
                f"m{point.marking_matrix_index:05d}-{variant}"
            )
            omega = point.target_omega
            yield {
                "schema_version": SCHEMA_VERSION,
                "config_sha256": digest,
                "row_id": row_id,
                "topology": point.topology,
                "stratum": _atlas_stratum(point.topology, q_abs, variant, payload),
                "atlas_target_index": point.target_index,
                "atlas_target_omega11": f"{omega[0, 0].real:+.17e}{omega[0, 0].imag:+.17e}j",
                "atlas_target_omega12": f"{omega[0, 1].real:+.17e}{omega[0, 1].imag:+.17e}j",
                "atlas_target_omega22": f"{omega[1, 1].real:+.17e}{omega[1, 1].imag:+.17e}j",
                "atlas_marking_word": point.marking_word,
                "atlas_marking_matrix_index": point.marking_matrix_index,
                "atlas_search_depth": point.search_depth,
                "atlas_tail_refined": point.tail_refined,
                "atlas_leading_q_max": point.leading_q_max,
                "atlas_best_valid_q_max": point.best_valid_q_max,
                "atlas_score_ratio": point.score_ratio,
                "atlas_overlap_chart": point.overlap_chart,
                "atlas_variant": variant,
                "q1": f"{q_values[0].real:+.17e}{q_values[0].imag:+.17e}j",
                "q2": f"{q_values[1].real:+.17e}{q_values[1].imag:+.17e}j",
                "q3": f"{q_values[2].real:+.17e}{q_values[2].imag:+.17e}j",
                "log_abs_q1": logs[0].real,
                "log_abs_q2": logs[1].real,
                "log_abs_q3": logs[2].real,
                "phase_q1": logs[0].imag,
                "phase_q2": logs[1].imag,
                "phase_q3": logs[2].imag,
                "q_min": min(q_abs),
                "q_max": max(q_abs),
                "geometry_margin": geometry.minimum_margin,
                "planned_backend": backend.backend,
                "precision_tier": backend.precision_tier,
                "backend_reason": backend.reason,
                "estimated_cost": backend.estimated_cost,
                "shard_id": _stable_shard(row_id, task_count),
            }


def _atomic_write_csv(path: Path, rows: Iterable[dict[str, object]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] | None = None
    count = 0
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", newline="") as handle:
            writer: csv.DictWriter | None = None
            for row in rows:
                if fieldnames is None:
                    fieldnames = list(row)
                    writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
                    writer.writeheader()
                assert writer is not None
                writer.writerow(row)
                count += 1
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise
    return count


def write_manifest(payload: dict[str, object], output_dir: Path) -> dict[str, object]:
    """Generate the design manifest only; no period-map backend is called."""

    useful_region = payload["useful_region"]  # type: ignore[index]
    if (
        not USEFUL_REGION_SELECTOR_IMPLEMENTED
        or useful_region.get("status") != "selector-implemented-and-certified"
    ):
        raise RuntimeError(
            "production manifest refused: implement and certify the six-dimensional "
            "theta/glasses hybrid-cover selector before writing q rows."
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "manifest.csv"
    pending_path = output_dir / "manifest.pending.csv"
    count = _atomic_write_csv(pending_path, iter_manifest_rows(payload))
    with pending_path.open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    selected_targets = {int(row["atlas_target_index"]) for row in rows}
    target_count = 1 << int(payload["atlas_design"]["target_sample_power"])  # type: ignore[index]
    selected_fraction = len(selected_targets) / float(target_count)
    required_fraction = float(
        payload["atlas_design"]["required_selected_target_fraction"]  # type: ignore[index]
    )
    if selected_fraction < required_fraction:
        pending_path.unlink()
        raise RuntimeError(
            "atlas selector coverage failed: "
            f"{len(selected_targets)}/{target_count}={selected_fraction:.8f} "
            f"is below {required_fraction:.8f}"
        )
    os.replace(pending_path, manifest_path)
    topology_counts: dict[str, int] = {}
    overlap_count = 0
    cusp_count = 0
    for row in rows:
        topology_counts[row["topology"]] = topology_counts.get(row["topology"], 0) + 1
        overlap_count += int(row["atlas_overlap_chart"].lower() == "true")
        cusp_count += int(row["atlas_variant"] != "base")
    summary = {
        "schema_version": SCHEMA_VERSION,
        "config_sha256": config_sha256(payload),
        "maximum_selector_row_count": nominal_point_count(payload),
        "manifest_point_count": count,
        "atlas_target_count": target_count,
        "selected_atlas_target_count": len(selected_targets),
        "selected_atlas_target_fraction": selected_fraction,
        "required_selected_atlas_target_fraction": required_fraction,
        "topology_row_counts": topology_counts,
        "overlap_row_count": overlap_count,
        "cusp_augmentation_row_count": cusp_count,
        "array_task_count": int(payload["array_task_count"]),
        "manifest": str(manifest_path),
        "computation_launched": False,
    }
    (output_dir / "manifest_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    (output_dir / "config.snapshot.json").write_text(json.dumps(payload, indent=2) + "\n")
    return summary


def describe(payload: dict[str, object]) -> dict[str, object]:
    return {
        "schema_version": SCHEMA_VERSION,
        "config_sha256": config_sha256(payload),
        "maximum_selector_row_count": nominal_point_count(payload),
        "atlas_target_count": 1 << int(payload["atlas_design"]["target_sample_power"]),  # type: ignore[index]
        "array_task_count": int(payload["array_task_count"]),
        "maximum_rows_per_task_before_selection": (
            nominal_point_count(payload) / int(payload["array_task_count"])
        ),
        "q_domain": payload["q_domain"],
        "useful_region": payload["useful_region"],
        "atlas_design": payload["atlas_design"],
        "schottky_all_small_q_max": payload["schottky_all_small_q_max"],
        "note": (
            "Description only: no atlas targets, manifest rows, or period matrices were computed."
        ),
    }


def run(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("describe", help="print counts and bounds without generating points")
    manifest_parser = subparsers.add_parser(
        "write-manifest", help="write q points but do not evaluate any period matrix"
    )
    manifest_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(list(argv) if argv is not None else None)
    payload = load_config(args.config)
    if args.command == "describe":
        print(json.dumps(describe(payload), indent=2))
    elif args.command == "write-manifest":
        print(json.dumps(write_manifest(payload, args.output_dir), indent=2))
    else:  # pragma: no cover
        raise AssertionError(args.command)


if __name__ == "__main__":
    run()
