"""Render the current C++/MPC PBW comparison and count-based estimates."""
from decimal import Decimal
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOTES = ROOT / 'Machine Notes'
FOLDER = ROOT / 'C++/results/direct_pbw_cpp_2026-09-12'


def scientific(value):
    number = Decimal(str(value))
    exponent = number.adjusted()
    return f'{number.scaleb(-exponent):.3f}' + r'\times10^{' + str(exponent) + '}'


def render():
    measured = json.loads((FOLDER/'timings.json').read_text())
    assert measured['status'] == 'completed'
    assert measured['precision_bits'] == 136 and measured['q_level_cutoffs'] == [5]*3
    assert all(r['status'] == 'completed' for r in measured['runs'])
    runs = {(r['algorithm'], r['mode']): r for r in measured['runs']}
    modes = ['ordinary', 'inserted']
    pbw = [runs['pbw_cpp', m] for m in modes]
    dv = [runs['double_virasoro_cpp', m] for m in modes]
    assert all(r['counts']['monomials'] == 396 for r in pbw)
    ratios = [p['wall_seconds']/d['wall_seconds'] for p, d in zip(pbw, dv)]
    comparison = {(r['reference'], r['mode']): r for r in measured['comparisons']}
    diffs = [comparison['fresh_cpp_double_virasoro', m] for m in modes]
    ports = [comparison['saved_python_pbw', m] for m in modes]
    lines = [r'% Generated by C++/tools/render_optimized_pbw_notes.py from fresh C++ measurements.',
        r'Both numerical implementations are C++17 with MPC at 40-digit working',
        r'precision (136 bits). At the same parameters, fresh runs with',
        r'$q_1,q_2,q_3$ each cut off at level 5 give the following full wall times.',
        r'Each result contains 396 monomials and 3,168 parity components, including',
        r'$q_1^5q_2^5q_3^5$. Double Virasoro includes all stages of physical-block',
        r'recovery. Processes are separate and sequential; numerical caches start',
        r'empty, within-run reuse is enabled, and compilation is excluded.',
        r'Python only launches the executables and compares saved outputs.',
        r'\begin{center}\small', r'\begin{tabular}{@{}lrrr@{}}', r'\toprule',
        r'Sector & C++ PBW (s) & C++ double Virasoro (s) & PBW/DV\\', r'\midrule']
    for sign, p, d, ratio in zip(['1', '-1'], pbw, dv, ratios):
        lines.append(r"$\eta\eta'=" + sign + '$ & ' + f'{p["wall_seconds"]:.2f} & '
                     f'{d["wall_seconds"]:.2f} & ' + '$' + f'{ratio:.2f}' + r'\times$\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{center}',
        r'The measured double-Virasoro advantage is modest at this cutoff:',
        '$' + f'{ratios[0]:.2f}' + r'\times$ and $' + f'{ratios[1]:.2f}' + r'\times$ in the two sectors.',
        r'These are single-run timings, not statistical performance bounds.',
        '', r'\paragraph{Direct C++ PBW implementation.}',
        r'The physical three-point tensors are evaluated by SCA Ward recursion and',
        r'contracted with inverse physical Gram matrices. The negative-sector',
        r'command uses the label \texttt{inserted} to match the other executable;',
        r'this direct PBW calculation itself contains no auxiliary insertion.',
        r'Descendant words are interned once and states use integer labels.',
        r'The implementation caches canonical words, levels, parities, binomial',
        r'coefficients and mode actions, sharing action data between the two vertex',
        r'signs. Ward values use three-integer keys. Each symmetric bilinear Gram',
        r'matrix is built from one triangle and its inverse is retained. When',
        r"$\eta=\eta'$, the second vertex reuses the first tensor. Successive",
        r'axis contractions index the tensors directly, with reusable MPC scratch',
        r'and no stored permutation tables. Output is serialized once.',
        '',
        r'Gram LU elimination and substitution use working precision throughout;',
        r'only pivot comparisons convert magnitudes to double. There is no',
        r'double-precision LU preconditioner in this direct PBW implementation.',
        r'The numerical tensors use bilinear, not Hermitian, contraction.',
        r'\begin{center}\small', r'\begin{tabular}{@{}lrr@{}}', r'\toprule',
        r"C++ PBW stage (s) & $\eta\eta'=1$ & $\eta\eta'=-1$\\", r'\midrule']
    for label, key in [('Gram entries', 'gram_entries'), ('Gram inversion', 'gram_inverse'),
                       ('Vertex tensors and Ward recursion', 'vertices'),
                       ('Tensor contractions', 'contractions'), ('Internal total', 'total')]:
        lines.append(label + ' & ' + ' & '.join(f'{r["timing_seconds"][key]:.3f}' for r in pbw) + r'\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{center}',
        r'Vertex construction accounts for ' + ' and '.join(
            f'{100*r["timing_seconds"]["vertices"]/r["timing_seconds"]["total"]:.1f}' + r'\%' for r in pbw) +
        r' of internal time. Peak resident memory is ' + ' and '.join(
            f'{r["memory"]["peak_rss_native_units"]/1e6:.1f}' for r in pbw) + r' MB (decimal).',
        '',
        r'The double-Virasoro benchmark includes the two latest CCY changes:',
        r'grouping inserted assembly by recursion shift and middle descendant',
        r'levels to reuse the amplitude times middle vertex; and dense complete-vertex',
        r'caches, with reusable MPC scratch during propagation. These evaluate',
        r'the same sum in \eqref{eq:forward-assemble}. Ordinary three-edge global',
        r'assembly retains its production formula. This isolated benchmark build',
        r'is separate from the executable used for the measured level-10 table above.',
        '', r'\paragraph{Coefficient comparison.}',
        r'All 3,168 components per sector were compared. For C++ PBW versus',
        r'C++ double Virasoro, the maximum scaled differences,',
        r'$|a-b|/\max(1,|a|,|b|)$, are $' + scientific(diffs[0]['maximum_scaled_difference']) + '$',
        'and $' + scientific(diffs[1]['maximum_scaled_difference']) + '$; the absolute maxima are',
        '$' + scientific(diffs[0]['maximum_absolute_difference']) + '$ and $' + scientific(diffs[1]['maximum_absolute_difference']) + '$.',
        r'This is agreement at roughly 20 digits on this scale, not 40 certified',
        r'output digits. To check the port separately, comparison with the saved',
        r'Python PBW coefficients gives maximum scaled differences $' + scientific(ports[0]['maximum_scaled_difference']) + '$',
        'and $' + scientific(ports[1]['maximum_scaled_difference']) + '$. No Python block was rerun.',
        '', r'\begingroup\raggedright',
        r'The direct code is \path{C++/include/ramond/direct_pbw.hpp}, with driver',
        r'\path{C++/drivers/pbw_main.cpp}. Timings, coefficients, comparison records',
        r'and source/build hashes are under',
        r'\path{C++/results/direct_pbw_cpp_2026-09-12/}.', r'\par\endgroup']
    (NOTES/'ramond_blocks_current_algorithm_optimized_pbw_comparison.tex').write_text('\n'.join(lines)+'\n')

    estimate = json.loads((FOLDER/'level10_estimate.json').read_text())
    assert estimate['precision_bits'] == 136 and estimate['new_physical_gram_ward_block_evaluations'] == 0
    forecasts = [next(f for f in estimate['forecasts'] if f['mode'] == m) for m in modes]
    counts = estimate['counts']
    production_data = json.loads((ROOT/'C++/results/per_edge_level10_2026-09-11/optimized_full_pipeline_40dps/timings.json').read_text())
    production = {r['mode']: r for r in production_data['runs']}
    projected_ratios = [f['constant_unit_cost_seconds']/production[m]['wall_seconds'] for f, m in zip(forecasts, modes)]
    rows = [(r"Vertex entries, $\eta\eta'=1$", 'vertex_entries_positive'),
            (r"Vertex entries, $\eta\eta'=-1$", 'vertex_entries_negative'),
            ('Contraction multiplications', 'contraction_products'),
            ('Gram triangle entries', 'gram_triangle_entries'), ('Cubic Gram proxy', 'gram_cube_proxy')]
    lines = [r'% Generated by C++/tools/render_optimized_pbw_notes.py from C++ stage timings and work counts.',
        r'\begin{center}\small', r'\begin{tabular}{@{}lrr@{}}', r'\toprule',
        r'Counted work & Independent level 5 & Independent level 10\\', r'\midrule']
    for label, key in rows:
        lines.append(label + ' & ' + f'{counts["5"][key]:,} & {counts["10"][key]:,}' + r'\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{center}',
        r'For Gram dimensions $d_1,d_2,d_3$, each level triple requires',
        r"$2d_1d_2d_3$ distinct vertex entries when $\eta=\eta'$ and",
        r"$4d_1d_2d_3$ when $\eta=-\eta'$, including both allowed parity",
        r'sectors. Successive Gram contractions and the final pairing use',
        r'$2d_1d_2d_3(d_1+d_2+d_3+1)$ complex multiplications. Distinct symmetric',
        r'Gram matrices require $d(d+1)/2$ entries each; $\sum d^3$ is an',
        r'inversion-cost proxy, not an exact operation count. The level-5 counts',
        r'agree with counters in the C++ run.',
        '',
        r'Vertex requests increase by a factor of 1,862 and contraction',
        r'multiplications by 16,605. Holding the measured C++ cost per entry or',
        r'product fixed, and scaling the other stages by their own work counts,',
        'gives $' + f'{forecasts[0]["constant_unit_cost_seconds"]/3600:.2f}' + '$ h and $' +
        f'{forecasts[1]["constant_unit_cost_seconds"]/3600:.2f}' + '$ h. Vertex evaluation contributes $' +
        f'{forecasts[0]["constant_unit_cost_stage_seconds"]["vertices"]/3600:.2f}' + '$ h and $' +
        f'{forecasts[1]["constant_unit_cost_stage_seconds"]["vertices"]/3600:.2f}' + '$ h;',
        'contractions contribute approximately $' + f'{forecasts[0]["constant_unit_cost_stage_seconds"]["contractions"]/3600:.2f}' +
        r'$ h in each sector and dominate this baseline.',
        r'Unassigned internal work and process overhead, which include tensor and',
        r'cache destruction, are scaled by the vertex-entry ratio as a proxy.',
        '',
        r'A sensitivity scenario scales only the vertex cost further by the',
        r'entry-weighted mean total level, which increases from $11.71$ to',
        r'$25.02$, a factor of $2.137$. This illustrates the possible cost of',
        r'longer Ward recursions; it does not count their internal operations.',
        r'The two scenarios are neither runtime bounds nor a confidence interval.',
        r'\begin{center}\small', r'\begin{tabular}{@{}lcc@{}}', r'\toprule',
        r"Independent level 10, 136 bits & $\eta\eta'=1$ & $\eta\eta'=-1$\\", r'\midrule',
        r'C++ double Virasoro, measured production & 6 min 57 s & 27 min 35 s\\',
        r'C++ double Virasoro, latest CCY projection & --- & $\sim19$ min\\',
        'C++ PBW, constant unit costs & ' + ' & '.join(f'{f["constant_unit_cost_seconds"]/3600:.1f} h' for f in forecasts) + r'\\',
        'C++ PBW, longer-Ward scenario & ' + ' & '.join(f'{f["level_weighted_ward_sensitivity_seconds"]/3600:.1f} h' for f in forecasts) + r'\\',
        r'\bottomrule', r'\end{tabular}', r'\end{center}',
        r'The constant-unit-cost PBW estimates are about ' + f'{projected_ratios[0]:.0f}' + ' and ' + f'{projected_ratios[1]:.0f}',
        r'times the measured C++ double-Virasoro wall times. This expected',
        r'advantage at level 10 is much larger than the measured level-5 advantage,',
        r'but no level-10 PBW run was performed. The 19-minute figure is a separate',
        r'projection from sampled Virasoro factors with the latest CCY changes,',
        r'weighted by the full branching workload; that full level-10 pipeline has',
        r'not been retimed. Equal working precision does not certify equal output accuracy.',
        '', r'\paragraph{Memory assumption.}',
        r'The estimates assume enough RAM to retain the caches without paging.',
        r'The current C++ Ward caches retain at least 659 million and 1.318 billion',
        r'distinct requested entries. Each has a 12-byte key within a 96-byte',
        r'key/value object and at least 48 additional bytes for the two 136-bit',
        r'mantissas on this platform. These objects and mantissas alone require',
        'approximately ' + ' and '.join(f'{f["memory_lower_bound"]["top_level_pair_and_mantissa_bytes"]/1e9:.0f}' for f in forecasts) + r' GB (decimal). Hash nodes, buckets,',
        r'additional internal Ward states, allocator overhead, mode-action caches',
        r'and tensor buffers add to this. No tensor-permutation tables are stored.',
        r'These are partial storage counts, not measured level-10 peak memory.',
        r'Insufficient RAM would require changing cache retention and re-estimating runtime.',
        '', r'\begingroup\raggedright',
        r'Integer counts, stage estimates, assumptions and provenance are in',
        r'\path{C++/results/direct_pbw_cpp_2026-09-12/level10_estimate.json}.',
        r'The latest CCY projection is recorded in',
        r'\path{C++/experiments/ccy_assembly_2026-09-12/measurements.json}.', r'\par\endgroup']
    (NOTES/'ramond_blocks_current_algorithm_per_edge_pbw.tex').write_text('\n'.join(lines)+'\n')


if __name__ == '__main__':
    render()
