"""Refresh LaTeX tables from completed independent-edge runs; evaluate no blocks."""
import json
from pathlib import Path
from render_optimized_pbw_notes import render as render_optimized_pbw_notes

ROOT = Path(__file__).resolve().parents[2]
FOLDER = ROOT / 'C++/results/per_edge_level10_2026-09-11'
NOTES = ROOT / 'Machine Notes'


def main():
    report = json.loads((FOLDER / 'optimized_full_pipeline_40dps/timings.json').read_text())
    assert report['status'] == 'completed' and report['dps'] == 40
    assert report['truncation'] == 'per-edge'
    runs = {r['mode']: r for r in report['runs']}
    ordered = [runs['ordinary'], runs['inserted']]
    assert all(r['level'] == 10 and r['coefficient_vectors'] == 2541 for r in ordered)
    stages = [('Initial mode actions', 'actions'), ('Outer branching recurrence', 'outer_ward'),
              ('Middle recurrence', 'middle'), ('Reduced CCY', 'ccy'),
              ('Virasoro products', 'products'), ('Branch assembly', 'assembly'),
              ('Direct fermion', 'auxiliary'), ('Sector division', 'division'),
              ('Schottky vacuum and square', 'schottky'), ('Vacuum restoration', 'restoration')]
    lines = [r'% Generated by C++/tools/render_per_edge_notes.py from completed run records.',
             r'These runs impose $N=10$ independently on each edge, retaining all',
             r'$2{,}541$ monomials and $20{,}328$ parity components in each sector.',
             r'They use 40 decimal digits of working precision (136 bits), with the',
             r'fermion Ward sums and Schottky series evaluated exactly. All table entries are seconds.',
             r'\begin{center}\small', r'\begin{tabular}{@{}lrr@{}}', r'\toprule',
             r"Stage & $\eta\eta'=1$ & $\eta\eta'=-1$\\", r'\midrule']
    for name, key in stages:
        lines.append(name + ' & ' + ' & '.join(f"{r['timing_seconds'][key]:.3f}" for r in ordered) + r'\\')
    overhead = [r['timing_seconds']['total'] - sum(r['timing_seconds'][k] for _, k in stages)
                for r in ordered]
    lines += ['Other pipeline overhead & ' + ' & '.join(f'{v:.3f}' for v in overhead) + r'\\',
              'Internal total & ' + ' & '.join(f"{r['timing_seconds']['total']:.3f}" for r in ordered) + r'\\',
              'Startup, serialization and exit & ' + ' & '.join(
                  f"{r['wall_seconds'] - r['timing_seconds']['total']:.3f}" for r in ordered) + r'\\',
              r'\midrule', 'Full wall time & ' + ' & '.join(
                  r'\textbf{' + f"{r['wall_seconds']:.3f}" + '}' for r in ordered) + r'\\',
              r'\bottomrule', r'\end{tabular}', r'\end{center}',
              r'The full wall times are \textbf{6 min 57 s} and \textbf{27 min 35 s}.',
              r'Other pipeline overhead is the difference between the independently timed',
              r'internal total and the named stages; it includes work and cache cleanup',
              r'outside their timers. Branching, including initial actions but excluding',
              r'the middle recurrence, takes $9.938$ s and $10.044$ s. The outer Ward',
              r'recurrence itself takes $0.441$ s and $0.450$ s.',
              r'\begin{center}\small', r'\begin{tabular}{@{}lrr@{}}', r'\toprule',
              r"Recorded work & $\eta\eta'=1$ & $\eta\eta'=-1$\\", r'\midrule']
    count_fields = [('Direct boundary values', 'direct_boundary_values'),
                    ('Stored recursive branching values', 'recursive_branching_values'),
                    ('Assembled branch tuples', 'branches'), ('Virasoro blocks', 'virasoro_blocks'),
                    ('Reused transposed products', 'transposed_products_reused'),
                    ('Global-seed summands', 'ccy_seed_terms'), ('CCY transitions', 'ccy_transitions')]
    for label, key in count_fields:
        lines.append(label + ' & ' + ' & '.join(f"{r['counts'][key]:,}" for r in ordered) + r'\\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{center}',
              r'The ordinary wall time was $508.004$ s before the latest CCY reuse changes;',
              r'its CCY stage decreased from $390.230$ s to $296.593$ s. The former',
              r'inserted run was interrupted and had projected to about $4.5$ hours.',
              r'That forecast is not a completed baseline measurement. Interrupted and',
              r'overlapping attempts are excluded from the tables above.',
              r'\subsubsection*{Directed checks and accuracy limits}',
              r'Both saved outputs contain the complete requested box and only finite',
              r'physical components. Source and executable hashes match the launch records.',
              r'The maximum recorded recovery-sector residuals are $2.226\times10^{-15}$',
              r'and $8.837\times10^{-16}$, respectively. These test sector consistency',
              r'before vacuum restoration, not independent physical-coefficient accuracy.',
              '',
              r'Comparing all $20{,}328$ ordinary components with the saved pre-change',
              r'40-digit result gives maximum scaled difference $2.107\times10^{-20}$',
              r'and absolute difference $8.907\times10^{-9}$; coefficients reach',
              r'$4.166\times10^{12}$. Here the scale is $\max(1,|a|,|b|)$.',
              r'This checks the implementation change at the same working precision.',
              r'The full level-10 inserted box has no completed pre-change or independent',
              r'reference; the new independent level-5 PBW comparison is reported below.',
              '',
              r'At independent cutoff 2, both physical pipelines were compared with saved',
              r'results on all 45 monomials; after the CCY optimization their scaled',
              r'differences from the saved pre-change box are below $2.97\times10^{-35}$.',
              r'Individual inserted Virasoro factors at edge cutoffs 6 and 8 agree with',
              r'the former implementation within $8.88\times10^{-32}$ in scaled difference.',
              r'Exact checks compare small Schottky and fermion boxes with projections of',
              r'their total-degree series and check the shifted-diagonal product on an',
              r'asymmetric domain. Those checks used stored physical reference blocks.',
              '',
              r'\begingroup\raggedright',
              r'The directed optimization evidence is saved under',
              r'\path{C++/results/ccy_vertex_reuse_2026-09-11/}; output inspection and',
              r'cutoff validation are in \path{C++/results/per_edge_level10_2026-09-11/}.',
              r'\par\endgroup']
    (NOTES / 'ramond_blocks_current_algorithm_per_edge_timings.tex').write_text('\n'.join(lines) + '\n')

    render_optimized_pbw_notes()
    print('Updated production timings, measured PBW comparison and current PBW estimates.')


if __name__ == '__main__':
    main()
