#!/usr/bin/env python3
"""Independent Human-convention PBW ingredients for the NS--R--R block.

This is the coefficientwise implementation of the Ramond theta-channel
formula in ``Human Notes/SCblock.tex``.  It keeps the three plumbing parities
open, in the component order

    p_NS + 2 p_R1 + 4 p_R2,

It supplies the auxiliary Majorana block and the finite-level NS--R--R PBW
block used by the certified production comparison, which measures

    enlarged = auxiliary star physical.

The authoritative double-Virasoro series is generated by
``full_ramond_block_runtime`` from Yuchen's ``L_1`` branching grid.  The
auxiliary ground vector is singular in four star-spectral channels, so
the forward identity is the unambiguous check; a full formal star quotient is
not unique without additional spin-structure data. The independent physical
side uses Ramond ground labels ``w^+,w^-`` from the start and evaluates the
PBW Gram matrices and super-Virasoro Ward forms in that basis. It does not use
the archived standalone direct-chi branching anchor, and no PBW-side
``(-1)^A`` multiplier is inserted.

All public level triples are twice-levels.  Thus the Ramond entries are even
and ``(a,b,c)`` represents the monomial
``q_NS**(a/2) q_R1**(b/2) q_R2**(c/2)``.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
from itertools import combinations
from pathlib import Path
import sys
from typing import Iterable, Mapping, Sequence

import numpy as np
import sympy as sp


THIS_DIR = Path(__file__).resolve().parent
CODE_DIR = THIS_DIR.parents[1]
for directory in (
    THIS_DIR,
    CODE_DIR / "c_Recursion",
    CODE_DIR / "genus_2_cross_channel",
    CODE_DIR / "ramond_branching_recursion",
):
    if str(directory) not in sys.path:
        sys.path.insert(0, str(directory))

from mixed_ns_ramond_descendant_blocks import NSVermaModule  # noqa: E402
from direct_state_check import (  # noqa: E402
    AuxiliaryThreePoint,
)
from ramond_pbw_generalized_ward import (  # noqa: E402
    GeneralizedNRRWard,
    RamondPBWModule,
)
from theta_star_algebra import star_multiply, theta_quadratic_sign  # noqa: E402
import compute_target as BRANCHING_RECURSION  # noqa: E402


Level = tuple[int, int, int]
ParityVector = tuple[complex, ...]
ComponentSeries = dict[Level, ParityVector]

ZERO_VECTOR: ParityVector = (0.0j,) * 8


class HumanAuxiliaryThreePoint(AuxiliaryThreePoint):
    """Majorana NS--R--R form satisfying the Human-Note zero-mode Ward rule."""

    def base_value(self, states):
        ground2 = states[1][1]
        ground3 = states[2][1]
        if ground2 != ground3:
            return 0.0j
        rho_00 = 1.0 + 0.0j
        # rho(1,psi_0 u^0,u^1)-i rho(1,u^0,psi_0 u^1)=0 and
        # psi_0 u^a=u^(1-a)/sqrt(2) imply rho_11=i rho_00.
        return rho_00 if ground2 == 0 else 1.0j * rho_00


def _exact_real(value: object) -> sp.Expr:
    """Convert a real input to a compact exact SymPy number."""

    if isinstance(value, sp.Expr):
        expression = value
    elif isinstance(value, Fraction):
        expression = sp.Rational(value.numerator, value.denominator)
    elif isinstance(value, float):
        expression = sp.Rational(str(value))
    else:
        expression = sp.sympify(value)
    if expression.is_real is False:
        raise ValueError("the exact NSRR branching backend currently requires real data")
    return sp.cancel(expression)


def level_triples(maximum_total_twice_level: int) -> Iterable[Level]:
    """Yield NSRR-compatible triples through the total twice-level cutoff."""

    cutoff = int(maximum_total_twice_level)
    if cutoff < 0:
        raise ValueError("the total twice-level cutoff must be nonnegative")
    for total in range(cutoff + 1):
        for ns_level in range(total + 1):
            for r1_level in range(0, total - ns_level + 1, 2):
                r2_level = total - ns_level - r1_level
                if r2_level % 2 == 0:
                    yield ns_level, r1_level, r2_level


def _add_vectors(left: Sequence[complex], right: Sequence[complex]) -> ParityVector:
    return tuple(complex(a) + complex(b) for a, b in zip(left, right))


def _put_component(
    series: ComponentSeries, levels: Level, component: int, value: complex
) -> None:
    current = list(series.get(levels, ZERO_VECTOR))
    current[int(component)] += complex(value)
    series[levels] = tuple(current)


def star_convolve_series(
    left: Mapping[Level, Sequence[complex]],
    right: Mapping[Level, Sequence[complex]],
    *,
    maximum_total_twice_level: int,
) -> ComponentSeries:
    """Multiply two truncated three-variable series in the R star algebra."""

    cutoff = int(maximum_total_twice_level)
    answer: ComponentSeries = {}
    for left_levels, left_vector in left.items():
        for right_levels, right_vector in right.items():
            levels = tuple(
                int(left_levels[edge]) + int(right_levels[edge])
                for edge in range(3)
            )
            if sum(levels) > cutoff:
                continue
            product = tuple(star_multiply(left_vector, right_vector))
            answer[levels] = _add_vectors(answer.get(levels, ZERO_VECTOR), product)
    return answer




def _distinct_mode_sets(total: int, allowed: Sequence[int]) -> tuple[tuple[int, ...], ...]:
    answer: list[tuple[int, ...]] = []
    for count in range(len(allowed) + 1):
        for subset in combinations(allowed, count):
            if sum(subset) == total:
                answer.append(tuple(sorted(subset, reverse=True)))
    return tuple(answer)


@lru_cache(maxsize=None)
def ns_fermion_states(twice_level: int) -> tuple[tuple[sp.Rational, ...], ...]:
    target = int(twice_level)
    modes = _distinct_mode_sets(target, tuple(range(1, target + 1, 2)))
    return tuple(
        tuple(sp.Rational(value, 2) for value in state) for state in modes
    )


@lru_cache(maxsize=None)
def ramond_fermion_states(
    level: int,
) -> tuple[tuple[tuple[sp.Integer, ...], int], ...]:
    target = int(level)
    modes = _distinct_mode_sets(target, tuple(range(1, target + 1)))
    return tuple(
        (tuple(sp.Integer(value) for value in state), ground)
        for state in modes
        for ground in (0, 1)
    )


def auxiliary_majorana_nsrr_series(
    *, maximum_total_twice_level: int
) -> ComponentSeries:
    """Sew the auxiliary Majorana NSRR block in the canonical spin frames."""

    modules = (
        BRANCHING_RECURSION.FreeFieldModule("NS", 1.4, 0.1),
        BRANCHING_RECURSION.FreeFieldModule("R", 1.4, 0.2),
        BRANCHING_RECURSION.FreeFieldModule("R", 1.4, 0.3),
    )
    form = HumanAuxiliaryThreePoint(modules)
    answer: ComponentSeries = {}
    for levels in level_triples(maximum_total_twice_level):
        ns_level, r1_twice, r2_twice = levels
        for first_modes in ns_fermion_states(ns_level):
            parity_ns = len(first_modes) % 2
            for second_modes, ground_1 in ramond_fermion_states(r1_twice // 2):
                parity_r1 = (len(second_modes) + ground_1) % 2
                for third_modes, ground_2 in ramond_fermion_states(r2_twice // 2):
                    parity_r2 = (len(third_modes) + ground_2) % 2
                    if (parity_ns + parity_r1 + parity_r2) % 2:
                        continue
                    rho = form.value(
                        (
                            tuple(int(2 * mode) for mode in first_modes),
                            (tuple(int(mode) for mode in second_modes), ground_1),
                            (tuple(int(mode) for mode in third_modes), ground_2),
                        )
                    )
                    if abs(rho) <= 1.0e-14:
                        continue
                    component = parity_ns | (parity_r1 << 1) | (parity_r2 << 2)
                    # Human Notes/SCblock.tex, free-fermion Ramond box:
                    # the first auxiliary word carries (-1)^mathsf A.
                    value = (
                        (-1) ** parity_ns
                        * theta_quadratic_sign(component)
                        * rho
                        * rho
                    )
                    _put_component(answer, levels, component, value)
    return answer


class HumanNSRRThetaOracle:
    """Direct PBW theta sewing in the literal Human-Note slot order NS,R,R."""

    def __init__(
        self,
        *,
        central_charge: sp.Expr,
        h_ns: sp.Expr,
        beta_r1: sp.Expr,
        beta_r2: sp.Expr,
        form_parity: int,
        primary_parity: int,
        etas: Sequence[int],
    ) -> None:
        self.central_charge = sp.sympify(central_charge)
        self.h_ns = sp.sympify(h_ns)
        self.betas = (sp.sympify(beta_r1), sp.sympify(beta_r2))
        self.r_weights = tuple(
            sp.cancel(self.central_charge / 24 - beta**2) for beta in self.betas
        )
        self.form_parity = int(form_parity)
        self.primary_parity = int(primary_parity)
        if self.primary_parity not in (0, 1):
            raise ValueError("primary_parity must be 0 or 1")
        self.etas = tuple(int(value) for value in etas)
        self.ns_module = NSVermaModule(
            c=complex(sp.N(self.central_charge, 60)),
            weight=complex(sp.N(self.h_ns, 60)),
        )
        self.r_modules = tuple(
            RamondPBWModule(weight, beta, self.central_charge)
            for weight, beta in zip(self.r_weights, self.betas)
        )
        self.forms = tuple(
            GeneralizedNRRWard(
                p_phi=self.primary_parity,
                form_parity=(
                    self.form_parity + self.primary_parity
                ) % 2,
                eta=eta,
                h_ns=self.h_ns,
                h_second=self.r_weights[0],
                h_third=self.r_weights[1],
                beta_second=self.betas[0],
                beta_third=self.betas[1],
                central_charge=self.central_charge,
            )
            for eta in self.etas
        )

    @staticmethod
    def _ns_word(state) -> tuple[tuple[str, sp.Expr], ...]:
        return tuple(
            (kind, sp.Rational(mode, 2)) for kind, mode in state
        )

    @lru_cache(maxsize=None)
    def ns_basis_inverse(self, twice_level: int):
        basis = tuple(self.ns_module.basis(int(twice_level)))
        inverse = np.linalg.inv(
            np.asarray(
                self.ns_module.gram_matrix(int(twice_level)), dtype=np.complex128
            )
        )
        return basis, inverse

    @lru_cache(maxsize=None)
    def r_basis_inverse(self, edge: int, level: int, parity: int):
        basis, gram = self.r_modules[int(edge)].gram_matrix(
            int(level), int(parity)
        )
        inverse = np.linalg.inv(
            np.asarray(gram.evalf(60).tolist(), dtype=np.complex128)
        )
        return tuple(basis), inverse

    @lru_cache(maxsize=None)
    def coefficient_components(
        self, ns_twice_level: int, r1_level: int, r2_level: int
    ) -> ParityVector:
        ns_twice_level = int(ns_twice_level)
        ns_basis, inverse_ns = self.ns_basis_inverse(ns_twice_level)
        ns_parity = ns_twice_level % 2
        first_eta_parity = (ns_parity + self.primary_parity) % 2
        answer = [0.0j] * 8
        for parity_r1 in (0, 1):
            parity_r2 = (
                self.form_parity + ns_parity + parity_r1
            ) % 2
            basis_r1, inverse_r1 = self.r_basis_inverse(
                0, int(r1_level), parity_r1
            )
            basis_r2, inverse_r2 = self.r_basis_inverse(
                1, int(r2_level), parity_r2
            )
            tensors = []
            for form in self.forms:
                tensor = np.empty(
                    (len(ns_basis), len(basis_r1), len(basis_r2)),
                    dtype=np.complex128,
                )
                for i, state_ns in enumerate(ns_basis):
                    word_ns = self._ns_word(state_ns)
                    for j, state_r1 in enumerate(basis_r1):
                        for k, state_r2 in enumerate(basis_r2):
                            tensor[i, j, k] = complex(
                                sp.N(
                                    form.value(
                                        word_ns,
                                        state_r1.word,
                                        state_r1.ground,
                                        state_r2.word,
                                        state_r2.ground,
                                    ),
                                    60,
                                )
                            )
                tensors.append(tensor)
            contracted = np.einsum(
                "abc,ad,be,cf,def->",
                tensors[0],
                inverse_ns,
                inverse_r1,
                inverse_r2,
                tensors[1],
                optimize=True,
            )
            component = (
                first_eta_parity
                | (parity_r1 << 1)
                | (parity_r2 << 2)
            )
            # The PBW block is already defined and evaluated in the
            # Human-Note w^+/w^- convention.  Convention transport belongs
            # only to the fusion coefficient and no extra PBW-side phase is
            # inserted here.
            answer[component] = theta_quadratic_sign(component) * contracted
        return tuple(complex(value) for value in answer)


def direct_pbw_nsrr_series(
    *,
    b: object,
    momenta: Sequence[object],
    form_parity: int,
    primary_parity: int = 0,
    etas: Sequence[int] = (1, 1),
    maximum_total_twice_level: int = 2,
) -> ComponentSeries:
    """Return the independent finite-level physical NSRR PBW block."""

    if len(momenta) != 3:
        raise ValueError("momenta must contain the NS, R1, and R2 momenta")
    b_exact = _exact_real(b)
    p_ns, p_r1, p_r2 = tuple(_exact_real(value) for value in momenta)
    q_value = sp.cancel(b_exact + 1 / b_exact)
    central_charge = sp.cancel(sp.Rational(3, 2) + 3 * q_value**2)
    h_ns = sp.cancel((q_value**2 / 4 - p_ns**2) / 2)
    oracle = HumanNSRRThetaOracle(
        central_charge=central_charge,
        h_ns=h_ns,
        beta_r1=p_r1 / sp.sqrt(2),
        beta_r2=p_r2 / sp.sqrt(2),
        etas=etas,
        form_parity=int(form_parity),
        primary_parity=int(primary_parity),
    )
    return {
        levels: oracle.coefficient_components(
            levels[0], levels[1] // 2, levels[2] // 2
        )
        for levels in level_triples(maximum_total_twice_level)
    }
