#!/bin/bash
set -euo pipefail
PYTHON_BIN="${PYTHON_BIN:-python3}"
BUNDLE_ROOT="$(cd "$(dirname "$0")" && pwd)"
export PYTHONPATH="${BUNDLE_ROOT}/plumbing:${BUNDLE_ROOT}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-/tmp/stringmc-matplotlib}"
mkdir -p "${MPLCONFIGDIR}"
cd "${BUNDLE_ROOT}"
echo "RUN plumbing/audit_genus0_one_to_two_amplitude_checks.py"
"${PYTHON_BIN}" "plumbing/audit_genus0_one_to_two_amplitude_checks.py"
echo "RUN plumbing/liouville_torus_checks.py"
"${PYTHON_BIN}" "plumbing/liouville_torus_checks.py"
echo "RUN plumbing/ccy_sphere_four_point_checks.py"
"${PYTHON_BIN}" "plumbing/ccy_sphere_four_point_checks.py"
echo "RUN plumbing/ccy_sphere_five_point_checks.py"
"${PYTHON_BIN}" "plumbing/ccy_sphere_five_point_checks.py"
echo "RUN plumbing/ccy_sphere_six_point_checks.py"
"${PYTHON_BIN}" "plumbing/ccy_sphere_six_point_checks.py"
echo "RUN plumbing/ccy_sphere_six_point_star_checks.py"
"${PYTHON_BIN}" "plumbing/ccy_sphere_six_point_star_checks.py"
echo "RUN plumbing/sphere_five_point_liouville_checks.py"
"${PYTHON_BIN}" "plumbing/sphere_five_point_liouville_checks.py"
echo "RUN plumbing/sphere_six_point_atlas_checks.py"
"${PYTHON_BIN}" "plumbing/sphere_six_point_atlas_checks.py"
echo "RUN plumbing/torus_two_point_blocks_checks.py"
"${PYTHON_BIN}" "plumbing/torus_two_point_blocks_checks.py"
echo "RUN plumbing/genus1_two_point_worldsheet_checks.py"
"${PYTHON_BIN}" "plumbing/genus1_two_point_worldsheet_checks.py"
echo "RUN plumbing/genus1_three_point_worldsheet_checks.py"
"${PYTHON_BIN}" "plumbing/genus1_three_point_worldsheet_checks.py"
echo "RUN plumbing/genus1_three_point_channel_atlas_checks.py"
"${PYTHON_BIN}" "plumbing/genus1_three_point_channel_atlas_checks.py"
echo "RUN plumbing/genus1_three_point_matrix_comparison_checks.py"
"${PYTHON_BIN}" "plumbing/genus1_three_point_matrix_comparison_checks.py"
echo "ALL CORE CHECKS PASSED"
